name: Update documentation web site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.token }}
      - name: set up node 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Deploy website on Github Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          ACCESS_TOKEN: ${{ secrets.token }}
          BRANCH: gh-pages
          FOLDER: .
